# Generated by Django 4.2.8 on 2023-12-12 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={
                "ordering": ("title",),
                "verbose_name": "astronomy_shows",
                "verbose_name_plural": "astronomy_shows",
            },
        ),
    ]
