# Generated by Django 4.2.8 on 2023-12-12 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_alter_astronomyshow_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ("title",)},
        ),
    ]
